/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmManterDepartamento.java
 *
 * Created on May 22, 2009, 10:50:36 AM
 */
package view;

import control.CtrManterDepartamento;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Departamento;

/**
 *
 * @author elio
 */
public class FrmManterDepartamento extends javax.swing.JFrame {
    //declaracao dos atributos

    CtrManterDepartamento ctrManterDepartamento;
    Departamento depart;

    /** Creates new form FrmManterDepartamento */
    public FrmManterDepartamento() {
        initComponents();
         //inicia os atributos
        ctrManterDepartamento = new CtrManterDepartamento();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoInserir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewDepartamentoList = new javax.swing.JList<Departamento>();
        botaoExcluir = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelArea = new javax.swing.JLabel();
        campoArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        botaoInserir.setText("Incluir");
        botaoInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoInserirMouseClicked(evt);
            }
        });

        viewDepartamentoList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        viewDepartamentoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDepartamentoListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewDepartamentoList);

        botaoExcluir.setText("Excluir");
        botaoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirMouseClicked(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAlterarMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Departamento"));

        labelNome.setText("Nome");

        labelArea.setText("Área");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelArea)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoArea)
                    .addComponent(campoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelArea))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoInserir)
                        .addGap(18, 18, 18)
                        .addComponent(botaoExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAlterar))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserir)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoAlterar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //carrega lista de departamentos
        DefaultListModel<Departamento> listModel = new DefaultListModel<>();
        List<Object> listDepartamento = new ArrayList<>();
        listDepartamento = ctrManterDepartamento.carregarDepartamentos();
        if (listDepartamento != null) {
            for (Object deptList : listDepartamento) {
                listModel.addElement((Departamento) deptList);
            }
            viewDepartamentoList.setModel(listModel);
        }
    }//GEN-LAST:event_formWindowActivated

    private void viewDepartamentoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDepartamentoListMouseClicked
        //recupera o departamento selecionado
        depart = viewDepartamentoList.getSelectedValue();

        //exibe os dados do departamento
        if (depart != null) {
            campoNome.setText(depart.getNome());
            campoArea.setText(depart.getArea());
        } else {
            JOptionPane.showMessageDialog(null, "Objeto não Encontrado!");
        }
    }//GEN-LAST:event_viewDepartamentoListMouseClicked

    private void botaoInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoInserirMouseClicked
         //atribui valores para o departamento
        depart = new Departamento();
        depart.setNome(campoNome.getText());
        depart.setArea(campoArea.getText());

        //inclui departamento
        if (ctrManterDepartamento.gravarDepartamento(depart) == 1) {
            JOptionPane.showMessageDialog(this, "Objeto persistido");
        } else if (ctrManterDepartamento.gravarDepartamento(depart) == 2) {
            JOptionPane.showMessageDialog(this, "Objeto não persistido");
        } else {
            JOptionPane.showMessageDialog(this, "Nome repetido");
        }
    }//GEN-LAST:event_botaoInserirMouseClicked

    private void botaoExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirMouseClicked
      //recupera o departamento selecionado
        depart = viewDepartamentoList.getSelectedValue();

        //exclui departamento
        if (depart != null) {
            if (ctrManterDepartamento.excluirDepartamento(depart)) {
                JOptionPane.showMessageDialog(null, "Objeto Exclu�do");
            } else {
                JOptionPane.showMessageDialog(null, "Objeto n�o exclu�do");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o Objeto");
        }
    }//GEN-LAST:event_botaoExcluirMouseClicked

    private void botaoAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAlterarMouseClicked
         //recupera o departamento selecionado
        depart = viewDepartamentoList.getSelectedValue();
        //altera o departamento
        if (depart != null) {
            depart.setNome(campoNome.getText());
            depart.setArea(campoArea.getText());

            if (ctrManterDepartamento.alterarDepartamento(depart)) {
                JOptionPane.showMessageDialog(this, "Objeto persistido");

            } else {
                JOptionPane.showMessageDialog(this, "Objeto n�o persistido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Objeto n�o localizado");
        }
    }//GEN-LAST:event_botaoAlterarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmManterDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoInserir;
    private javax.swing.JTextField campoArea;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelNome;
    private javax.swing.JList<Departamento> viewDepartamentoList;
    // End of variables declaration//GEN-END:variables
}
