/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmViewHome.java
 *
 * Created on May 22, 2009, 10:50:36 AM
 */
package view;

import control.Controller;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.*;

import dao.AuthorsDAO;
import dao.BookDAO;
import dao.PublishersDAO;
import model.Authors;
import model.Books;
import model.Publishers;
import util.JFrameUtil;
import javax.swing.GroupLayout.Alignment;
import java.awt.FlowLayout;
import javax.swing.border.TitledBorder;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author elio
 */
public class FrmViewHome extends javax.swing.JFrame {
    //declaracao dos atributos
    private ArrayList<Books> listaDeLivros = new ArrayList<>();
    private ArrayList<Authors> listaDeAutores = new ArrayList<>();
    private ArrayList<Publishers> listaDeEditoras = new ArrayList<>();
    private Books livroSelecionado;
    private Authors autorSelecionado;
    private Publishers editorSelecionado;
    

    /** Creates new form FrmManterDepartamento */
    public FrmViewHome() {
        initComponents();
         //inicia os atributos

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaPrincipal = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        abaEdicao = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEditLivro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        seletorLivros = new javax.swing.JComboBox<>();
        livrosAbas = new javax.swing.JTabbedPane();
        livrosPainelEditar = new javax.swing.JPanel();
        campoTituloLivro = new javax.swing.JTextField();
        campoPrecoLivro = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        botaoAlterarLivro = new javax.swing.JButton();
        livrosPainelIncluirDeletar = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        botaoIncluirLivro = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        campoIncluirTitulo = new javax.swing.JTextField();
        labelIncluirTitulo = new javax.swing.JLabel();
        campoIncluirPreco = new javax.swing.JTextField();
        labelIncluirPreco = new javax.swing.JLabel();
        seletorIncluirAutor = new javax.swing.JComboBox<>();
        labelIncluirAutor = new javax.swing.JLabel();
        campoIncluirIsbn = new javax.swing.JTextField();
        labelIsbn = new javax.swing.JLabel();
        botaoExcluirLivro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        abaVisualizacoes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeVisualizacaoLivros = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDeVisualizacaoAutores = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaDeVisualizacaoEditora = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        abaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaPrincipalMouseClicked(evt);
            }
        });

        tabelaEditLivro.setAutoCreateRowSorter(true);
        tabelaEditLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaEditLivro.setColumnSelectionAllowed(true);
        tabelaEditLivro.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaEditLivro);

        jLabel1.setText("Livro selecionado:");

        seletorLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorLivrosActionPerformed(evt);
            }
        });

        livrosPainelEditar.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar valores"));
        livrosPainelEditar.setToolTipText("");

        labelPreco.setText("Preço");

        labelTitulo.setText("Titulo");

        botaoAlterarLivro.setText("Alterar");
        botaoAlterarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAlterarLivroMouseClicked(evt);
            }
        });
        botaoAlterarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout livrosPainelEditarLayout = new javax.swing.GroupLayout(livrosPainelEditar);
        livrosPainelEditar.setLayout(livrosPainelEditarLayout);
        livrosPainelEditarLayout.setHorizontalGroup(
            livrosPainelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPainelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(livrosPainelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo)
                    .addComponent(labelPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(livrosPainelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAlterarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPrecoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        livrosPainelEditarLayout.setVerticalGroup(
            livrosPainelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPainelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(livrosPainelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(livrosPainelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreco)
                    .addComponent(campoPrecoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoAlterarLivro)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        livrosAbas.addTab("Ediar", livrosPainelEditar);

        botaoIncluirLivro.setText("Incluir");
        botaoIncluirLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoIncluirLivroMouseClicked(evt);
            }
        });
        botaoIncluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirLivroActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar valores"));
        jPanel10.setToolTipText("");

        labelIncluirTitulo.setText("Titulo");

        labelIncluirPreco.setText("Preço");

        seletorIncluirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorIncluirAutorActionPerformed(evt);
            }
        });

        labelIncluirAutor.setText("Autor");

        labelIsbn.setText("Isbn");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(labelIncluirAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seletorIncluirAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(labelIncluirPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(campoIncluirPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(labelIncluirTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoIncluirTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(labelIsbn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoIncluirIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIncluirTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIncluirTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIncluirIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIsbn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seletorIncluirAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIncluirAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIncluirPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIncluirPreco))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIncluirLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoIncluirLivro)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout livrosPainelIncluirDeletarLayout = new javax.swing.GroupLayout(livrosPainelIncluirDeletar);
        livrosPainelIncluirDeletar.setLayout(livrosPainelIncluirDeletarLayout);
        livrosPainelIncluirDeletarLayout.setHorizontalGroup(
            livrosPainelIncluirDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPainelIncluirDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        livrosPainelIncluirDeletarLayout.setVerticalGroup(
            livrosPainelIncluirDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPainelIncluirDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        livrosAbas.addTab("Incluir", livrosPainelIncluirDeletar);

        botaoExcluirLivro.setText("Excluir");
        botaoExcluirLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirLivroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(livrosAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoExcluirLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(seletorLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(170, 170, 170))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(seletorLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoExcluirLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(livrosAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        abaEdicao.addTab("Livros", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        abaEdicao.addTab("Autor", jPanel5);
        
        EditoraAbas_1 = new JTabbedPane();
        
        botaoExcluirEditora = new JButton();
        botaoExcluirEditora.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		botaoExcluirEditoraMouseClicked(e);
        	}
        });
        botaoExcluirEditora.setText("Excluir");
        
        jScrollPane2_1 = new JScrollPane();
        
        jLabel1_1 = new JLabel();
        jLabel1_1.setText("Editora selecionada:");
        
        seletorEditoras = new JComboBox<String>();
        seletorEditoras.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		seletorIncluirEditoraActionPerformed(e);
        	}
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addComponent(jLabel1_1, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(seletorEditoras, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jScrollPane2_1, GroupLayout.PREFERRED_SIZE, 415, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(288)
        					.addComponent(botaoExcluirEditora, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(EditoraAbas_1, GroupLayout.PREFERRED_SIZE, 439, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap(29, Short.MAX_VALUE)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1_1)
        				.addComponent(seletorEditoras, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(15)
        			.addComponent(jScrollPane2_1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addComponent(botaoExcluirEditora)
        			.addGap(6)
        			.addComponent(EditoraAbas_1, GroupLayout.PREFERRED_SIZE, 202, GroupLayout.PREFERRED_SIZE)
        			.addGap(19))
        );
        
        editorasPainelEditar = new JPanel();
        editorasPainelEditar.setBorder(new TitledBorder(null, "Editar valores", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        EditoraAbas_1.addTab("Editar", null, editorasPainelEditar, null);
        editorasPainelEditar.setLayout(null);
        
        JLabel labelNomeAlterar = new JLabel();
        labelNomeAlterar.setText("Nome");
        labelNomeAlterar.setBounds(20, 43, 239, 14);
        editorasPainelEditar.add(labelNomeAlterar);
        
        JLabel labelUrlAlterar = new JLabel();
        labelUrlAlterar.setText("Url");
        labelUrlAlterar.setBounds(20, 69, 239, 14);
        editorasPainelEditar.add(labelUrlAlterar);
        
        JButton btnAlterar = new JButton();
        btnAlterar.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		botaoAlterarEditoraMouseClicked(e);
        	}
        });
        btnAlterar.setText("Alterar");
        btnAlterar.setBounds(57, 104, 202, 23);
        editorasPainelEditar.add(btnAlterar);
        
        textFieldUrlEditar = new JTextField();
        textFieldUrlEditar.setBounds(57, 66, 202, 20);
        editorasPainelEditar.add(textFieldUrlEditar);
        
        textFieldNomeEditar = new JTextField();
        textFieldNomeEditar.setBounds(57, 40, 202, 20);
        editorasPainelEditar.add(textFieldNomeEditar);
        
        editorasPainelIncluir = new JPanel();
        editorasPainelIncluir.setBorder(new TitledBorder(null, "Incluir valores", TitledBorder.LEADING, TitledBorder.TOP, null, null));
        EditoraAbas_1.addTab("Incluir", null, editorasPainelIncluir, null);
        editorasPainelIncluir.setLayout(null);
        
        JLabel labelNome_1 = new JLabel();
        labelNome_1.setText("Nome");
        labelNome_1.setBounds(10, 32, 239, 14);
        editorasPainelIncluir.add(labelNome_1);
        
        JLabel labelPreco_1 = new JLabel();
        labelPreco_1.setText("Url");
        labelPreco_1.setBounds(10, 58, 239, 14);
        editorasPainelIncluir.add(labelPreco_1);
        
        
        
        textFieldIncluirUrl = new JTextField();
        textFieldIncluirUrl.setBounds(47, 55, 202, 20);
        editorasPainelIncluir.add(textFieldIncluirUrl);
        
        textFieldIncluirNome = new JTextField();
        textFieldIncluirNome.setBounds(47, 29, 202, 20);
        editorasPainelIncluir.add(textFieldIncluirNome);
        
       
        JButton botaoIncluirEditora = new JButton();
        botaoIncluirEditora.addMouseListener(new java.awt.event.MouseAdapter() {
        	@Override
        	public void mouseClicked(java.awt.event.MouseEvent e) {
        		AdicionarEditoras(e);
        	}});
        botaoIncluirEditora.setText("Incluir");
        botaoIncluirEditora.setBounds(47, 93, 202, 23);
        editorasPainelIncluir.add(botaoIncluirEditora);
        
        tabelaEditEditora = new JTable();
        jScrollPane2_1.setViewportView(tabelaEditEditora);
        jPanel6.setLayout(jPanel6Layout);

        abaEdicao.addTab("Editora", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaEdicao)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        abaPrincipal.addTab("Editar", jPanel3);

        tabelaDeVisualizacaoLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaDeVisualizacaoLivros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelaDeVisualizacaoLivrosFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDeVisualizacaoLivros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        abaVisualizacoes.addTab("Livros", jPanel1);

        tabelaDeVisualizacaoAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabelaDeVisualizacaoAutores);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        abaVisualizacoes.addTab("Autores", jPanel7);

        tabelaDeVisualizacaoEditora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabelaDeVisualizacaoEditora);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        abaVisualizacoes.addTab("Editora", jPanel8);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaVisualizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaVisualizacoes)
                .addContainerGap())
        );

        abaPrincipal.addTab("Visualizar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaPrincipal)
                .addContainerGap())
        );

        pack();
    }
    
    
    private void AdicionarEditoras(java.awt.event.MouseEvent evt)
    {
    	boolean camposInValidos = textFieldIncluirNome.getText().isEmpty() ||
				textFieldIncluirUrl.getText().isEmpty();
		        campoIncluirIsbn.getText().isEmpty();
		        if (camposInValidos){
		            JOptionPane.showMessageDialog(this, "Existem campos vazios");
		        } else {
		            Controller<Publishers> controller = new Controller<Publishers>(Publishers.class, new PublishersDAO());

		            Publishers novaEditora = new Publishers();
		            novaEditora.setName(textFieldIncluirNome.getText());
		            novaEditora.setUrl(textFieldIncluirUrl.getText());
		           

		            int retorno = controller.gravarDados(novaEditora);

		            if (retorno == 1) {
		                JOptionPane.showMessageDialog(this, "Editora adicionadoa");
		                carregarEditoras();
		            } else if (retorno == 2) {
		                JOptionPane.showMessageDialog(this, "Editora não adicionado");
		            } else {
		                JOptionPane.showMessageDialog(this, "Editora já existe");
		            }
		            textFieldIncluirNome.setText("");
		            textFieldIncluirUrl.setText("");
	}
    }

    private void carregarLivros() {
        listaDeLivros = new JFrameUtil<Books>(Books.class, new BookDAO()).carregarLivros(listaDeLivros);
        seletorLivros.removeAllItems();
        for (Books b : listaDeLivros) {
            seletorLivros.addItem(b.getTitle());
        }
    }
    
    
    private void carregarEditoras() {
    	listaDeEditoras = new JFrameUtil<Publishers>(Publishers.class, new PublishersDAO()).carregarEditoras(listaDeEditoras);
    	seletorEditoras.removeAllItems();
        for (Publishers b : listaDeEditoras) {
            seletorEditoras.addItem(b.getName());
        }
    }

    private void carregarAutores() {
        listaDeAutores = new JFrameUtil<Authors>(Authors.class, new AuthorsDAO()).carregarAutores(listaDeAutores);
        seletorIncluirAutor.removeAllItems();
        for (Authors a : listaDeAutores) {
            seletorIncluirAutor.addItem(a.getFullName());
        }
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    	carregarEditoras();
        carregarLivros();
        carregarAutores();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void abaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaPrincipalMouseClicked
        // TODO add your handling code here:
        if (abaPrincipal.getSelectedIndex() == 1 ){
            if (abaVisualizacoes.getSelectedIndex() == 0) {
                listaDeLivros = new JFrameUtil<Books>(Books.class, new BookDAO()).carregarLivros(listaDeLivros);
                tabelaDeVisualizacaoLivros
                        .setModel(new JFrameUtil<Books>(Books.class, new BookDAO())
                                .carregarLivrosNaTabela(new ArrayList<>(listaDeLivros)));
            }
            if (abaVisualizacoes.getSelectedIndex() == 2) {
                listaDeEditoras = new JFrameUtil<Publishers>(Publishers.class, new PublishersDAO()).carregarEditoras(listaDeEditoras);
                tabelaDeVisualizacaoEditora
                        .setModel(new JFrameUtil<Publishers>(Publishers.class, new PublishersDAO())
                                .carregarEditorasNaTabela(new ArrayList<>(listaDeEditoras)));
            }
        }
    }//GEN-LAST:event_abaPrincipalMouseClicked

    private void seletorIncluirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorIncluirAutorActionPerformed
        listaDeAutores.forEach((e) -> {
            if (e.getFullName().equals(seletorIncluirAutor.getSelectedItem())) {
                autorSelecionado = e;
            }
        });
    }//GEN-LAST:event_seletorIncluirAutorActionPerformed
    private void seletorIncluirEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorIncluirAutorActionPerformed
        listaDeEditoras.forEach((e) -> {
            if (e.getName().equals(seletorEditoras.getSelectedItem())) {
                editorSelecionado = e;
                textFieldNomeEditar.setText(editorSelecionado.getName().trim());
                textFieldUrlEditar.setText(editorSelecionado.getUrl().trim());
                
                tabelaEditEditora
                .setModel(new JFrameUtil<Publishers>(Publishers.class, new PublishersDAO())
                    .carregarEditorasNaTabela(new ArrayList<>(Arrays.asList(editorSelecionado))));

                tabelaEditEditora.getColumnModel().getColumn(0).setPreferredWidth(200);
                
            }
        });
    }
    private void botaoIncluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoIncluirLivroActionPerformed

    private void botaoIncluirLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIncluirLivroMouseClicked

        boolean camposInValidos = campoIncluirTitulo.getText().isEmpty() ||
        campoIncluirPreco.getText().isEmpty() ||
        campoIncluirIsbn.getText().isEmpty() ||
        seletorIncluirAutor.getSelectedItem() == null;
        if (camposInValidos){
            JOptionPane.showMessageDialog(this, "Existem campos vazios");
        } else {
            Controller<Books> controller = new Controller<Books>(Books.class, new BookDAO());

            livroSelecionado = new Books();
            livroSelecionado.setTitle(campoIncluirTitulo.getText());
            livroSelecionado.setIsbn(campoIncluirIsbn.getText());
            livroSelecionado.setPublisherId(autorSelecionado.getAuthorId());
            livroSelecionado.setPrice(Double.parseDouble(campoIncluirPreco.getText()));

            int retorno = controller.gravarDados(livroSelecionado);

            if (retorno == 1) {
                JOptionPane.showMessageDialog(this, "Livro adicionado!");
            } else if (retorno == 2) {
                JOptionPane.showMessageDialog(this, "Livro não adicionado");
            } else {
                JOptionPane.showMessageDialog(this, "Livro já existe");
            }
        }
    }//GEN-LAST:event_botaoIncluirLivroMouseClicked

    private void botaoExcluirLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirLivroMouseClicked
        // TODO add your handling code here:
        if (livroSelecionado != null) {
            Controller<Books> controller = new Controller<Books>(Books.class, new BookDAO());
            if (controller.excluirDado(livroSelecionado)){
                JOptionPane.showMessageDialog(null, "Livro Excluído");
            } else {
                JOptionPane.showMessageDialog(null, "Livro não excluído");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um livro para deleta-lo");
        }
    }//GEN-LAST:event_botaoExcluirLivroMouseClicked
    
    private void botaoExcluirEditoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirLivroMouseClicked
        // TODO add your handling code here:
        if (editorSelecionado != null) {
            Controller<Publishers> controller = new Controller<Publishers>(Publishers.class, new PublishersDAO());
            if (controller.excluirDado(editorSelecionado)){
                JOptionPane.showMessageDialog(null, "Editora Excluído");
                carregarEditoras();
            } else {
                JOptionPane.showMessageDialog(null, "Editora não excluído");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Editora para deleta-la");
        }
    }
    private void botaoAlterarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAlterarLivroActionPerformed

    private void botaoAlterarLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAlterarLivroMouseClicked
   
        Controller<Books> controller = new Controller<Books>(Books.class, new BookDAO());
        if (livroSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Objeto não encontrado!");
        } else {
            livroSelecionado.setTitle(textFieldNomeEditar.getText());
            livroSelecionado.setPrice(Double.parseDouble(campoPrecoLivro.getText()));

            if (controller.alterarDado(livroSelecionado)) {
                JOptionPane.showMessageDialog(this, "Objeto persistido");
            } else {
                JOptionPane.showMessageDialog(this, "Objeto não persistido");
            }
            
        }
        carregarLivros();
    }//GEN-LAST:event_botaoAlterarLivroMouseClicked
    
    private void botaoAlterarEditoraMouseClicked(java.awt.event.MouseEvent evt) {
        Controller<Publishers> controller = new Controller<Publishers>(Publishers.class, new PublishersDAO());
        if (editorSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Objeto não encontrado!");
        } else {
        	editorSelecionado.setName(textFieldNomeEditar.getText());
        	editorSelecionado.setUrl(textFieldUrlEditar.getText());

            if (controller.alterarDado(editorSelecionado)) {
                JOptionPane.showMessageDialog(this, "Objeto persistido");
                carregarEditoras();
            } else {
                JOptionPane.showMessageDialog(this, "Objeto não persistido");
            }
        }
        carregarLivros();
    }

    private void seletorLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorLivrosActionPerformed
        // TODO add your handling code here:
        listaDeLivros.forEach((e) -> {
            if (e.getTitle() == seletorLivros.getSelectedItem()) {
                livroSelecionado = e;
                tabelaEditLivro
                .setModel(new JFrameUtil<Books>(Books.class, new BookDAO())
                    .carregarLivrosNaTabela(new ArrayList<>(Arrays.asList(livroSelecionado))));

                tabelaEditLivro.getColumnModel().getColumn(0).setPreferredWidth(200);
            }
        });
    }//GEN-LAST:event_seletorLivrosActionPerformed

    private void tabelaDeVisualizacaoLivrosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaDeVisualizacaoLivrosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaDeVisualizacaoLivrosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaEdicao;
    private javax.swing.JTabbedPane abaPrincipal;
    private javax.swing.JTabbedPane abaVisualizacoes;
    private javax.swing.JButton botaoAlterarLivro;
    private javax.swing.JButton botaoExcluirLivro;
    private javax.swing.JButton botaoIncluirLivro;
    private javax.swing.JTextField campoIncluirIsbn;
    private javax.swing.JTextField campoIncluirPreco;
    private javax.swing.JTextField campoIncluirTitulo;
    private javax.swing.JTextField campoPrecoLivro;
    private javax.swing.JTextField campoTituloLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelIncluirAutor;
    private javax.swing.JLabel labelIncluirPreco;
    private javax.swing.JLabel labelIncluirTitulo;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTabbedPane livrosAbas;
    private javax.swing.JPanel livrosPainelEditar;
    private javax.swing.JPanel livrosPainelIncluirDeletar;
    private javax.swing.JComboBox<String> seletorIncluirAutor;
    private javax.swing.JComboBox<String> seletorLivros;
    private javax.swing.JTable tabelaDeVisualizacaoAutores;
    private javax.swing.JTable tabelaDeVisualizacaoEditora;
    private javax.swing.JTable tabelaDeVisualizacaoLivros;
    private javax.swing.JTable tabelaEditLivro;
    private JTabbedPane EditoraAbas_1;
    private JButton botaoExcluirEditora;
    private JScrollPane jScrollPane2_1;
    private JLabel jLabel1_1;
    private JComboBox<String> seletorEditoras;
    private JTable tabelaEditEditora;
    private JPanel editorasPainelEditar;
    private JPanel editorasPainelIncluir;
    private JTextField textFieldIncluirUrl;
    private JTextField textFieldIncluirNome;
    private JTextField textFieldUrlEditar;
    private JTextField textFieldNomeEditar;
}
